<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Model\ParcelOrderInterface;

/**
 * ParcelOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcelOrderRepository extends \Doctrine\ORM\EntityRepository
{

	public function delete(ParcelInterface $parcelOrder) { 
		$em = $this->getEntityManager();
		$em->remove($parcelOrder);
		$em->flush();
    } 

    function findAllUnassigned()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT po FROM AppBundle:ParcelOrder po WHERE NOT EXISTS (SELECT t FROM AppBundle:Task t WHERE t.id = po.id)'
        )->getResult();
    }

	public function save(ParcelorderInterface $parcelorder) {
		$em = $this->getEntityManager();
        	$em->persist($parcelorder);
        	$em->flush();
    }
}
