# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
services:
    authentication_handler:
        class: AppBundle\Handler\AuthenticationHandler
        arguments:  ["@jms_serializer"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }