app_parcel_order:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\ParcelOrderController'
    name_prefix: api_1_parcelorder_

app_user:
    type: rest
    prefix: /v1
    resource: 'AppBundle\Controller\UserController'
    name_prefix: api_1_user_
