parameters:
    parcel.class: AppBundle\Entity\Parcel
    parcelorder.class: AppBundle\Entity\ParcelOrder
    postman.class: AppBundle\Entity\Postman
    addressdata.class: AppBundle\Entity\AddressData

services:
    parcelorder_emailsender.handler:
        class: AppBundle\Handler\ParcelOrderSendEmailHandler
        arguments: [ '@twig','@mailer' ]
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    parcel_form.handler:
        class: AppBundle\Handler\ParcelFormHandler
        arguments: ['@doctrine.orm.entity_manager', %parcel.class%, '@form.factory', 'AppBundle\Form\ParcelType']
    parcelorder_form.handler:
        class: AppBundle\Handler\ParcelOrderFormHandler
        arguments: ['@doctrine.orm.entity_manager', %parcelorder.class%, '@form.factory', 'AppBundle\Form\ParcelOrderType']
    addressdata_form.handler:
        class: AppBundle\Handler\AddressFormHandler
        arguments: ['@doctrine.orm.entity_manager', %addressdata.class%, '@form.factory', 'AppBundle\Form\AddressDataType']
    postman_form.handler:
        class: AppBundle\Handler\PostmanFormHandler
        arguments: ['@doctrine.orm.entity_manager', %postman.class%, '@form.factory', 'AppBundle\Form\PostmanType']
    authentication_handler:
        class: AppBundle\Handler\AuthenticationHandler
        arguments:  ["@router"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    user_form.handler:
        class: AppBundle\Handler\UserFormHandler
        arguments: ['@service_container']